### ISSUE TITLE
unable to compile on my own

### ISSUE THREAD

**Issue by AVitg** [SoBadFish/BedWar#15]
Hi, 
thanks for providing this nice BedWars plugin.
I tried to compile the plugin on my linux machine, but i am still learning and maybe my build sysem is not setup correctly.
However adding Lombok to pom dependencies fixed the compile error.
Now i can compile on my linux environment. (Ubuntu 22)
Thanks for merging my PR #14

**Comment by SoBadFish** [comment]
Sure, Thank you for your advice
