### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by apoorslime** [SoBadFish/BedWar#2]
# Update 

Update dependencies for Minecraft **1.19.20**
Version protocol: **554**

#### Information about my server
**`This server is running Nukkit git-b391d4d 「」 implementing API version 1.0.14 for Minecraft: BE v1.19.20** (protocol version 544)`**

### console error

`16:23:40 [FATAL] Could not load plugin "BedWar": Unknown dependency`

`16:23:40 [FATAL] Could not load plugin "BedWar": Circular dependency detected`

**Comment by stevei5mc** [comment]
ScoreboardAPI plugin install?

**Comment by SoBadFish** [comment]
try again
