### ISSUE TITLE
计分板图标功能

### ISSUE THREAD

**Issue by GouDan888** [SoBadFish/BedWar#3]
Unicode
![2934731631-2745182168-02B708B9995472ADA0E22A58927F059F](https://user-images.githubusercontent.com/49330438/188927440-596ba2e8-e817-4120-96ba-b842ca3d02f0.jpg)
![2934731631-2423905356-3839E58BAC7885EB310B4F8F4D091EEC](https://user-images.githubusercontent.com/49330438/188927454-e42665e8-0a90-42a5-ba05-c1f384c85a4a.jpg)

**Comment by GouDan888** [comment]
![R~K06_VYGFGOD}0A679{1CU](https://user-images.githubusercontent.com/49330438/188933419-1f1ba94d-2ecf-40ab-9b80-0119b04d8456.png)

**Comment by stevei5mc** [comment]
自定义计分板显示?

**Comment by GouDan888** [comment]
只要咸鱼在红队前面加一项 红 的文字我们就能替换成图标

**Comment by GouDan888** [comment]
BoatGames分支已实现
