### ISSUE TITLE
添加快捷发言

### ISSUE THREAD

**Issue by stevei5mc** [SoBadFish/BedWar#9]
添加快捷发言，以便快速与队友沟通

**Comment by GouDan888** [comment]
Won't you add it yourself？

**Comment by stevei5mc** [comment]
> Won't you add it yourself？

SuKaBuLe

**Comment by GouDan888** [comment]
> > 不会自己加吗？
> 
> SuKaBuLe

苏卡不列，是俄语词组“Сука блядь”的音译。指母狗、坏蛋，女性性工作者。属于非常严重的侮辱性粗口词语。

**Comment by stevei5mc** [comment]
> > > 不会自己加吗？
> > 
> > 
> > SuKaBuLe
> 
> 苏卡不列，是俄语词组“Сука блядь”的音译。指母狗、坏蛋，女性性工作者。属于非常严重的侮辱性粗口词语。

你直接说中文我都没有那么的气，都是中国人你**直接说英文，你个****，好像显得你好高大上啊，我祝你身体健康万事如意心想事成

**Comment by GouDan888** [comment]
6

**Comment by stevei5mc** [comment]
> 6

南无阿弥陀佛 
罪过
